#!/bin/bash

case "$OSTYPE" in
  solaris*) echo "Solaris OS is not supported" ;;
  darwin*)  source <(curl -sL https://raw.githubusercontent.com/Jacke/-/main/scripts/install-mac.sh) ;;
  linux*)   source <(curl -sL https://raw.githubusercontent.com/Jacke/-/main/scripts/install-linux.sh) ;;
  bsd*)     echo "BSD OS is not supported" ;;
  msys*)    echo "WINDOWS OS is not supported" ;;
  cygwin*)  echo "WINDOWS OS is not supported" ;;
  *)        echo "$OSTYPE OS is not supported" ;;
esac